[workspace]
resolver = "2"

members = [
    "crates/dinedash-auth",
    "crates/dinedash-customer",
    "crates/dinedash-order",
    "crates/dinedash-payment",
    "crates/dinedash-restaurant",
    "crates/dinedash-security",
]
