version: "3.9"

services:
  customer-cache:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6380"
    networks:
      - dinedash-network

  customer-db:
    image: postgres:9.5.10
    restart: always
    ports:
      - "5432:5432"
    networks:
      - dinedash-network
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  order-cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dinedash-network

  order-db:
    image: postgres:9.5.10
    restart: always
    ports:
      - "5433:5433"
    networks:
      - dinedash-network
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
