version: "3.9"

services:
  order:
    restart: always
    build: "services/order"
    ports:
      - "8000:8000"
    networks:
      - food-delivery-network
    depends_on:
      - order-cache
      - order-db

  order-cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - food-delivery-network

  order-db:
    image: postgres:9.5.10
    restart: always
    ports:
      - "5432:5432"
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
