version: "3.9"

include:
  - common.yaml

services:
  order:
    restart: always
    build: "crates/dinedash-order"
    ports:
      - "8000:8000"
    networks:
      - food-delivery-network
    depends_on:
      - order-cache
      - order-db
  customer:
    restart: always
    build: "crates/dinedash-customer"
    ports:
      - "9000:9000"
    networks:
      - food-delivery-network
    depends_on:
      - customer-cache
      - customer-db

networks:
  food-delivery-network:
